language: android

android:
  components:
    - tools
    - android-28
    - extra-android-m2repository

script:
  - ./gradlew app:clean app:testDebug jacocoTestReport --continue --no-daemon

after_success:
  - bash <(curl -s https://codecov.io/bash)
